### ISSUE TITLE
compiling issue for linux

### ISSUE THREAD

**Issue by lhr2523** [ARM-software/vulkan_best_practice_for_mobile_developers#10]
Hi,
when i am compiling the source code for linux platform, I met lots of issues:
vulkan_best_practice_for_mobile_developers/third_party/glm/glm/gtx/hash.hpp:72:14: error: ‘tquat’ is not a member of ‘glm’
  struct hash<glm::tquat<T,Q>>

usr/include/c++/4.9/bits/functional_hash.h:58:12: error: provided for ‘template<class _Tp> struct std::hash’
     struct hash;

/usr/include/c++/4.9/bits/unordered_map.h:121:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vkb::CommandType> >, std::__detail::__is_noexcept_hash<vkb::CommandType, std::hash<vkb::CommandType> > > >’
       typedef typename _Hashtable::iterator  iterator;

So there should has g++ version required ? and how to fix the third party issue ? I am using Ubuntu 14.04

**Comment by AttilioProvenzano-ARM** [comment]
Hi,
this could be due to a bug with GCC (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60970) which was  fixed in version 6.1+. Could you try compiling it with a newer version?

**Comment by cristian-szabo-arm** [comment]
Hi,

We are testing internally for Linux on Ubuntu 18.04 which comes with GCC v7.3. 
Looking at the C++ 14 features supported by GCC 4.9 it looks like is not a compatible to build the project.

Let us know if you need more help.

Thanks,
Chris

**Comment by lhr2523** [comment]
Hi ,
Thanks, I am using ubuntu 14.04 with gcc 4.9. So I think you should mention the build environment in readme which will be more helpful.

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

That's right, it's better to mention it in the readme. Just created https://github.com/ARM-software/vulkan_best_practice_for_mobile_developers/pull/12 which specifies a tested compiler version, plus the C++14 requirement.
Thanks for your feedback!
