### ISSUE TITLE
One Image cause to create new one DescriptorSet.....Is it reasonable? 

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan_best_practice_for_mobile_developers#19]
One Image cause to create new one DescriptorSet.....Is it reasonable?

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

We try to create the minimum amount of descriptor sets and reuse them as much as possible. In `device.cpp` there is a `request_descriptor_set` function which tries to get a descriptor set from cache with the corresponding buffer and image bindings.

So it's true that one image causes the creation of a new descriptor set, but only the first time, then it's cached and reused. :)

An alternative approach would be to keep a fixed set of descriptor sets and update them every frame with new buffer/image bindings. Is that what you were suggesting?
The cache-and-reuse approach is expected to be more efficient, but we plan to make a sample on descriptor set handling to confirm this.

Hope that helps!

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Thank you very much.
