### ISSUE TITLE
If I will update texture,  the number of  new descriptors  is 3 x (number of old descriptors) ?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan_best_practice_for_mobile_developers#20]
thank you

**Comment by AttilioProvenzano-ARM** [comment]
Hi,
This increase in descriptors shouldn't happen, I'm not quite sure what could be causing it.
What do you mean exactly by updating a texture? Could you share which functions are you calling specifically?

Thanks!

**Comment by flowerdancedatou** [comment]
In  "ARM Vulkan SDK".


void RotatingTexture::initPerFrame(unsigned numBackbuffers)
{
	VkDevice device = pContext->getDevice();

	for (unsigned i = 0; i < numBackbuffers; i++)
	{
		// Create one uniform buffer per swapchain frame. We will update the uniform buffer every frame
		// and we don't want to stomp on a uniform buffer already in flight.
		PerFrame frame;
		frame.uniformBuffer = createBuffer(nullptr, sizeof(mat4), VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT);

		// Allocate descriptor set from a pool.
		static const VkDescriptorPoolSize poolSizes[2] = {
			{ VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1 }, { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1 },
		};

		VkDescriptorPoolCreateInfo poolInfo = { VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO };
		poolInfo.poolSizeCount = 2;
		poolInfo.pPoolSizes = poolSizes;
		poolInfo.maxSets = 1;
		VK_CHECK(vkCreateDescriptorPool(device, &poolInfo, nullptr, &frame.descriptorPool));

		VkDescriptorSetAllocateInfo allocInfo = { VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO };
		allocInfo.descriptorPool = frame.descriptorPool;
		allocInfo.descriptorSetCount = 1;
		allocInfo.pSetLayouts = &setLayout;
		VK_CHECK(vkAllocateDescriptorSets(device, &allocInfo, &frame.descriptorSet));

		// Write our uniform and texture descriptors into the descriptor set.
		VkWriteDescriptorSet writes[2] = {
			{ VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET }, { VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET },
		};

		VkDescriptorBufferInfo bufferInfo = { frame.uniformBuffer.buffer, 0, sizeof(mat4) };
		VkDescriptorImageInfo imageInfo = { texture.sampler, texture.view, texture.layout };

		writes[0].dstSet = frame.descriptorSet;
		writes[0].dstBinding = 0;
		writes[0].descriptorCount = 1;
		writes[0].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
		writes[0].pImageInfo = &imageInfo;

		writes[1].dstSet = frame.descriptorSet;
		writes[1].dstBinding = 1;
		writes[1].descriptorCount = 1;
		writes[1].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
		writes[1].pBufferInfo = &bufferInfo;

		vkUpdateDescriptorSets(device, 2, writes, 0, nullptr);

		perFrame.push_back(frame);
	}
}

**Comment by flowerdancedatou** [comment]
Above.  X 3

**Comment by flowerdancedatou** [comment]
PerFrame hava one descriptor pool and  descriptor set............  Is it not necessary?

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Please help me.  Thank you very much.

**Comment by flowerdancedatou** [comment]
I  think It is can avoid the updateDescriptor cause problems.  By why is is  x3 pools...............

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

Thanks for sharing more details - now I understand the question. :)

If you want to make changes to a texture, you will need to keep copies of it to avoid breaking GPU pipelining, that's where the `3x # of descriptors` comes from.
If you only have a single copy of the texture you will have to wait for the previous frame to finish before starting the next one.

In the code you posted this approach is done for uniform buffers, as explained in this comment:
> 	// Create one uniform buffer per swapchain frame. We will update the uniform buffer every frame
> 	// and we don't want to stomp on a uniform buffer already in flight.

Regarding the use of one descriptor pool per frame, it is not _strictly_ necessary in this case but it's still very good to have. If you create your descriptor pool without the `FREE_DESCRIPTOR_SET_BIT` flag, it means you can only free the pool via `vkResetDescriptorPool`.
If you use only a single pool for all frames, you will have to wait idle before freeing. If you use several descriptor pools instead, you'll be able to free them for the frames that are not currently in flight.

I also recommend reading the section on "Descriptor sets and layouts" of our Mali GPU Best Practices PDF (https://developer.arm.com/solutions/graphics/developer-guides/mali-gpu-best-practices), there's some more interesting information in there.

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Thanks you very much.
