### ISSUE TITLE
I have a problem  about  creating and rendering the resources in runtime.

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan_best_practice_for_mobile_developers#23]
Assume I only use  one queue.  I load a texture  and  send  "create and transfer" commands to the queue,  and I don't wait the queue idle. Next time,  I send "rendering"  commands that it is use the texture to the queue.  I consider  it has many Concurrent risks.  Because 
the transport of the queue is guaranteed to be serial and the execution of the commands is parallel.      Do you think I understand it right?  Thank you.

**Comment by flowerdancedatou** [comment]
And  I ask a question about fence.  The fence is signaled ， 
Is It meaning all commands are transferred completely? 
or  Is It meaning all commands are executed completely?

**Comment by AttilioProvenzano-ARM** [comment]
Hi,

Regarding the first question, you are right that there is a concurrency risk. If you don't specify any synchronization, you have no guarantee that the transfer will be complete when the rendering begins.
You could add a pipeline barrier between the transfer and the shader stage in which you are going to use the image (you will need a pipeline barrier for the layout transition anyway).
If you're uploading many textures, for example when loading a new scene, it might just be easier to submit all the transfers and wait idle.

About fences: if it's the fence you get from `vkQueueSubmit`, yes, it means that commands are executed completely.
Actually it means even more than that! If the fence is signaled it means that all commands from all previous submissions are executed completely. :) 


> When a fence is submitted to a queue as part of a queue submission command, it defines a memory dependency on the batches that were submitted as part of that command, and defines a fence signal operation which sets the fence to the signaled state.
> 
> The first synchronization scope includes every batch submitted in the same queue submission command. **Fence signal operations that are defined by vkQueueSubmit additionally include in the first synchronization scope all commands that occur earlier in submission order**.
>

**Comment by flowerdancedatou** [comment]
@AttilioProvenzano-ARM  Thank you very much. I have more power to do my work.
