### ISSUE TITLE
Having trouble run the .exe file

### ISSUE THREAD

**Issue by wednesday818** [ARM-software/vulkan_best_practice_for_mobile_developers#28]
I couldn't run vulkan_best_practice.exe nor all samples independently.

After I successfully built the vulkan_best_practice and every single samples, when I tried to run the vulkan_best_practice.exe file it would flash then closed.

When I tried to run a single sample using Visual Studio, I'll get the "Microsoft C++ exception : docopt::DocoptLanguageError"

Am I doing anything wrong?

**Comment by ryanoshea-arm** [comment]
Hi there,

What command line samples did you provide when running the program?

Thanks!

**Comment by wednesday818** [comment]
Hi~ 

I've tried "build\windows\vulkan_best_practice\bin\Release\AMD64\vulkan_best_practice.exe" and "cmake --build build --config Debug --target afbc_app" on the cmd. Something would flash and close directly.

Then I set the afbc project under the Entrypoints folder in the Visual Studio to Start Up Project. I built it then run it with the "play" icon. That's the time I get this "docopt::DocoptLanguageError".

Thank you.

**Comment by ryanoshea-arm** [comment]
Hi,

The vulkan best practice binary cannot be run by double clicking the .exe as it requires the command line arguments, see more information in the usage section of the README [here](https://github.com/ARM-software/vulkan_best_practice_for_mobile_developers#usage).

Regarding the entry points, we've discovered a bug in this situation and hope to publish a fix by the end of today. If you need to run the AFBC sample now, then execute the best practices with the following command line arguement "--sample afbc".

Apologies for any inconvenience this may cause you.

**Comment by ZandroFargnoli** [comment]
> Hi~
> 
> I've tried "build\windows\vulkan_best_practice\bin\Release\AMD64\vulkan_best_practice.exe" and "cmake --build build --config Debug --target afbc_app" on the cmd. Something would flash and close directly.
> 
> Then I set the afbc project under the Entrypoints folder in the Visual Studio to Start Up Project. I built it then run it with the "play" icon. That's the time I get this "docopt::DocoptLanguageError".
> 
> Thank you.

@wednesday818 Hi there, could you please try run `build\windows\vulkan_best_practice\bin\Release\AMD64\vulkan_best_practice.exe afbc` for me and report what happens?

The reason the Window is opening and closing is because this is not the intended use of the Vulkan Best Practice, so its exiting after the argument parsing fails (it is expecting you to give something). Please check out the link @ryanoshea-arm has given you to see some examples of how to use the best practices. 

As for the entrypoints, we have a hotfix for them that will be published to **master** shortly!

Thank you

p.s. here is the full usage string for your convenience:

```
Usage:
	vulkan_best_practice <sample>
	vulkan_best_practice (--sample <arg> | --test <arg> | --batch <arg>) [--benchmark <frames>] [--width <arg>] [--height <arg>] [--hide]
	vulkan_best_practice --help

Options:
	--help                    Show this screen.
	--sample SAMPLE_ID        Run sample.
	--test TEST_ID            Run test.
	--batch CATEGORY_NAME     Run all samples within a category, specify 'all' to run all.
	--benchmark FRAMES        Run app under benchmark mode for n amount of frames.
	--width WIDTH             The width of the screen if visible [default: 1280].
	--height HEIGHT           The height of the screen if visible [default: 720].
	--hide                    Hides the window if possible.```

**Comment by wednesday818** [comment]
@ryanoshea-arm  @ZandroFargnoli  

"build\windows\vulkan_best_practice\bin\Release\AMD64\vulkan_best_practice.exe afbc"

This works!! Thank you guys so much~  You save my day!!
