### ISSUE TITLE
When  A uniform is being used  by gpu, and I change the uniform by host. Is it ok?

### ISSUE THREAD

**Issue by flowerdancedatou** [ARM-software/vulkan_best_practice_for_mobile_developers#30]
When  A uniform is being used  by gpu, and I change the uniform by host. Is it ok?

**Comment by flowerdancedatou** [comment]
I use vkMap.... to change the uniform buffer.

**Comment by AttilioProvenzano-ARM** [comment]
Hi!

Changing a uniform while the GPU is using it is dangerous from a synchronization standpoint: you cannot know if the GPU will read the data before or after the update, so the behaviour of your app would be inconsistent.

The spec says:

> The descriptor set contents bound by a call to vkCmdBindDescriptorSets may be consumed during host execution of the command, or during shader execution of the resulting draws, or any time in between. Thus, the contents must not be altered (overwritten by an update command, or freed) between when the command is recorded and when the command completes executing on the queue. The contents of pDynamicOffsets are consumed immediately during execution of vkCmdBindDescriptorSets. Once all pending uses have completed, it is legal to update and reuse a descriptor set.

If you want to change the uniform buffer data across frames without breaking synchronization, you'll have to replicate those data in some way. One way to do so without major changes to your code would be to create a larger uniform buffer (e.g. 3x the size for 3 frames) and bind it as a dynamic uniform buffer, changing the dynamic offset for each frame.

A quick note on `vkMapMemory`: allocating memory for each buffer via `vkAllocateMemory` might be really slow and there's a cap on the total number of allocations, plus mapping memory is a costly operation. The intended usage for an app is to allocate a big chunk of memory, keep it mapped and manage it.

If you want a drop-in replacement for memory management which follows these best practices, check out [VMA](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator). Its API is similar to Vulkan's so it probably won't require any major changes to your code.

Hope that helps! :)

**Comment by flowerdancedatou** [comment]
Thank you very much.^_^
