### ISSUE TITLE
Detecting screen orientation chage

### ISSUE THREAD

**Issue by TheMostDiligent** [ARM-software/vulkan_best_practice_for_mobile_developers#36]
Hello!

I was reading an article about surface rotation, and it was very helpful - thank you. However, I am struggling with rotation detection. The article suggests to [handle APP_CMD_CONTENT_RECT_CHANGED event](https://github.com/ARM-software/vulkan_best_practice_for_mobile_developers/blob/master/samples/performance/surface_rotation/surface_rotation_tutorial.md#rotation-in-android), however if you take a look at native_app_glue.c file from the most recent NDK (21.1), you will find out that the event is never generated. Similarly, `APP_CMD_WINDOW_RESIZED` is also a dead event.
The only one that is really generated is `APP_CMD_CONFIG_CHANGED`, but this one is very inconsistent: on some devices it is generated before the surface has been rotated, on others - after.
I was trying to compare window dimensions, but, again, on some devices the window size changes before the surface size changes.

I can handle `SUBOPTIMAL` error code, but I am looking for the method that will also work for GLES.

Thank you!

**Comment by PavelRudko-ARM** [comment]
Hi! 
Yes `APP_CMD_CONTENT_RECT_CHANGED` is not generated by default. This is already reported [here](https://github.com/android/ndk/issues/1139) and looks like it will work properly in NDK 22.
However, this works:
`app->activity->callbacks->onContentRectChanged = on_content_rect_changed;`
You can see this in the `AndroidPlatform` class. In this callback the event `APP_CMD_CONTENT_RECT_CHANGED` is then dispatched and handled in `on_app_cmd`.
So try using onContentRectChanged.
Please note, that this repository is now moved to [KhronosGroup/Vulkan-Samples](https://github.com/KhronosGroup/Vulkan-Samples).
The tutorial and code was updated, so check out the new repository. 
I have also created an [issue](https://github.com/KhronosGroup/Vulkan-Samples/issues/113) related to your question.
Hope that helps!

**Comment by TheMostDiligent** [comment]
@PavelRudko-ARM Thanks, this is very useful! Is `APP_CMD_CONTENT_RECT_CHANGED` guaranteed to be generated after the surface orientation has actually changed so that the swap chain?

**Comment by TomAtkinsonArm** [comment]
Hi @TheMostDiligent, [onContentRectChanged](https://developer.android.com/ndk/reference/struct/a-native-activity-callbacks#public-attributes_1) Is called when "The rectangle in the window in which content should be placed has changed."

`onContentRectChanged` is transformed to `APP_CMD_CONTENT_RECT_CHANGED` by android_native_app_glue.h in ndk version 22+. If you would like to still use `APP_CMD_CONTENT_RECT_CHANGED` you could always re-implement the [ndk 22 version](https://android-review.googlesource.com/c/platform/ndk/+/1180321/3/sources/android/native_app_glue/android_native_app_glue.c#386) for older versions of the ndk. It would require a check to see if the callback is set, if not then set the re-implemented version :)

**Comment by TomAtkinsonArm** [comment]
So to specifically answer your question. When this event fires the Swapchain can be resized
