### ISSUE TITLE
Broken link in afbc_tutorial

### ISSUE THREAD

**Issue by TheMostDiligent** [ARM-software/vulkan_best_practice_for_mobile_developers#37]
Hi!
Just FYI the [link to Arm framebuffer compression](https://github.com/ARM-software/vulkan_best_practice_for_mobile_developers/blob/master/samples/performance/afbc/afbc_tutorial.md#further-reading) in afbc_tutorial article is broken.

**Comment by JoseEmilio-ARM** [comment]
Thank you! Note that we move development to

https://github.com/KhronosGroup/Vulkan-Samples

I'll re-open the issue there: https://github.com/KhronosGroup/Vulkan-Samples/issues/117

**Comment by TheMostDiligent** [comment]
> Note that we moved development to

You may want to update the link to this repo on your [Vulkan best practices](https://community.arm.com/developer/tools-software/graphics/b/blog/posts/vulkan-best-practices-for-mobile-developers).
